[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

  [functions.pdf-to-image]
    handler = "pdf-to-image"
    runtime = "nodejs16.x"
    timeout = 60
